---
- hosts: all

  become: yes
  become_method: sudo
  remote_user: ubuntu

  tasks:
    - name: upload to s3
      amazon.aws.aws_s3:
         bucket: "publish-artifacts-java"
         object: "/LoginWebApp-1.war"
         src: "/target/LoginWebApp-1.war"
         mode: put
         overwrite: no
