---
- hosts: all

  become: yes
  become_method: sudo
  remote_user: ubuntu
  vars:
   ansible_python_interpreter: /usr/bin/python3
  tasks:
   - debug: var=ansible_host
   - name: upload to s3
     aws_s3:
        bucket: "publish-artifacts-java"
        object: "/LoginWebApp-1.war"
        src: "/target/LoginWebApp-1.war"
        mode: put
        
        #overwrite: no
